keys:
  - &admin_laplace age1gtv3y5adpd50mh9q57kh5rawe3crdqn0jq02ajmrf5ak7j974vhs7zmzdk
  - &neovenezia age15dxmet4kqe859f5ezqrl9desj9897yqkjxps6l2md5yeyylu5yuqyzthlz

creation_rules:
  - path_regex: secrets/.*\.yaml$
    key_groups:
      - age:
          - *admin_laplace
          - *neovenezia
