apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeeringPolicy
metadata:
  name: bgp-peering
spec:
  nodeSelector:
    matchLabels:
      node-role.kubernetes.io/control-plane: "true"
  
  virtualRouters:
    - localASN: 64512
      exportPodCIDR: true
      neighbors:
        # Your router's BGP config
        - peerAddress: "192.168.1.1/32"
          peerASN: 64512
          
      serviceSelector:
        matchExpressions:
          - key: somekey
            operator: NotIn
            values: ['never-used-value']