apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: main-pool
spec:
  cidrs:
    - cidr: "192.168.1.240/28"  # 16 IPs for LoadBalancers
  serviceSelector:
    matchLabels:
      io.cilium/lb-pool: main