apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 24h
  url: https://grafana.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: loki
      version: "5.x.x"
      sourceRef:
        kind: HelmRepository
        name: grafana
  
  values:
    loki:
      auth_enabled: false
      
      commonConfig:
        replication_factor: 1
      
      storage:
        type: filesystem
      
      schemaConfig:
        configs:
          - from: 2024-01-01
            store: tsdb
            object_store: filesystem
            schema: v12
            index:
              prefix: index_
              period: 24h
    
    # Single instance mode
    deploymentMode: SingleBinary
    
    singleBinary:
      replicas: 1
      persistence:
        enabled: true
        size: 20Gi
    
    # Disable unnecessary components for single binary
    read:
      replicas: 0
    write:
      replicas: 0
    backend:
      replicas: 0
---
# Promtail to ship logs
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: promtail
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: promtail
      version: "6.x.x"
      sourceRef:
        kind: HelmRepository
        name: grafana
  
  values:
    config:
      clients:
        - url: http://loki:3100/loki/api/v1/push